language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - npm install -g newman

script:
  - go test -v ./...
  - newman run ./provider-driven/Libberfy.postman_collection.json

after_success:
  - bash <(curl -s https://codecov.io/bash)  