language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt install nodejs npm
  - npm install -g newman

script:
  - go test -v ./...
  - newman run ./provider-driven/Libberfy.postman_collection.json